language: swift
os: osx
osx_image: xcode10.3
before_install:
  - gem install xcpretty
before_script:
  - set -o pipefail
script:
  - xcodebuild test -project ./GridView.xcodeproj -scheme GridViewTests -configuration Debug -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=12.4,name=iPhone 8' | xcpretty -c
notifications:
  email: false
